name: "Test"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: "Install PNPM"
        with:
          run_install: false

      - name: "Install Node"
        uses: actions/setup-node@v5
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Test with coverage"
        run: pnpm run coverage

      - name: "Upload coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
